/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer.Frames;

import com.company.Main.Admin;
import com.company.Main.AdminMenu;
import com.company.Main.Category;
import com.company.Main.Customer;
import com.company.Main.Location;
import com.company.Main.Register;
import com.company.Main.RestaurantOwner;
import com.company.Main.RestaurantOwnerMenu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class log_in extends javax.swing.JFrame {

    /**
     * Creates new CustomerForm log_in
     */
    public log_in() {
        initComponents();
        setResVisible(false);
        fillCategoryAndLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        signup_panel = new javax.swing.JPanel();
        customer = new javax.swing.JRadioButton();
        owner = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        res_name_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        email_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        combo_categories = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        num_txt = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        combo_locations = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pass_txt = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        email_txt2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        customer2 = new javax.swing.JRadioButton();
        res_owner2 = new javax.swing.JRadioButton();
        admin2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pass_txt2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/Frames/talabat logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Your everyday , right away ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 570));

        content.setLayout(new java.awt.CardLayout());

        signup_panel.setBackground(new java.awt.Color(32, 33, 35));
        signup_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer.setBackground(new java.awt.Color(32, 33, 35));
        buttonGroup1.add(customer);
        customer.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        customer.setForeground(new java.awt.Color(204, 204, 204));
        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        signup_panel.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 16));

        owner.setBackground(new java.awt.Color(32, 33, 35));
        buttonGroup1.add(owner);
        owner.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        owner.setForeground(new java.awt.Color(204, 204, 204));
        owner.setText("Restaurant Owner");
        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });
        signup_panel.add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 16));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Restaurant Name");
        signup_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        res_name_txt.setBackground(new java.awt.Color(32, 33, 35));
        res_name_txt.setBorder(null);
        res_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_name_txtActionPerformed(evt);
            }
        });
        signup_panel.add(res_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 170, 36));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Name");
        signup_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 13, -1, -1));

        name_txt.setBackground(new java.awt.Color(32, 33, 35));
        name_txt.setBorder(null);
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        signup_panel.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 37, 384, 36));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(94, 42, 14));
        signup_panel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, 384, 10));

        email_txt.setBackground(new java.awt.Color(32, 33, 35));
        email_txt.setBorder(null);
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        signup_panel.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 121, 384, 36));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Email");
        signup_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 97, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(94, 42, 14));
        signup_panel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 164, 384, 10));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Password");
        signup_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 178, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(94, 42, 14));
        signup_panel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 170, 10));

        jSeparator11.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator11.setForeground(new java.awt.Color(94, 42, 14));
        signup_panel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 245, 384, 10));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Category");
        signup_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        combo_categories.setBackground(new java.awt.Color(0, 0, 0));
        signup_panel.add(combo_categories, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 170, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Phone number");
        signup_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        num_txt.setBackground(new java.awt.Color(32, 33, 35));
        num_txt.setBorder(null);
        num_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_txtActionPerformed(evt);
            }
        });
        signup_panel.add(num_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 170, 36));

        jSeparator12.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator12.setForeground(new java.awt.Color(94, 42, 14));
        signup_panel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 170, 10));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Location");
        signup_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        combo_locations.setBackground(new java.awt.Color(0, 0, 0));
        signup_panel.add(combo_locations, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 180, 30));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Already have an account ? ");
        signup_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 72, 0));
        jLabel6.setText("Sign in");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        signup_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        pass_txt.setBackground(new java.awt.Color(32, 33, 35));
        pass_txt.setBorder(null);
        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        signup_panel.add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 380, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("          SIGN UP");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        signup_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 200, 60));

        content.add(signup_panel, "card2");

        login_panel.setBackground(new java.awt.Color(32, 33, 35));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Email");

        email_txt2.setBackground(new java.awt.Color(32, 33, 35));
        email_txt2.setBorder(null);
        email_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txt2ActionPerformed(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator13.setForeground(new java.awt.Color(94, 42, 14));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Password");

        jSeparator14.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator14.setForeground(new java.awt.Color(94, 42, 14));

        customer2.setBackground(new java.awt.Color(32, 33, 35));
        buttonGroup2.add(customer2);
        customer2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        customer2.setForeground(new java.awt.Color(204, 204, 204));
        customer2.setText("Customer");
        customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer2ActionPerformed(evt);
            }
        });

        res_owner2.setBackground(new java.awt.Color(32, 33, 35));
        buttonGroup2.add(res_owner2);
        res_owner2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        res_owner2.setForeground(new java.awt.Color(204, 204, 204));
        res_owner2.setText("Restaurant Owner");
        res_owner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_owner2ActionPerformed(evt);
            }
        });

        admin2.setBackground(new java.awt.Color(32, 33, 35));
        buttonGroup2.add(admin2);
        admin2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        admin2.setForeground(new java.awt.Color(204, 204, 204));
        admin2.setText("Admin");
        admin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("          SIGN IN");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Don't have an account? ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 72, 0));
        jLabel9.setText("Sign up");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        pass_txt2.setBackground(new java.awt.Color(32, 33, 35));
        pass_txt2.setBorder(null);
        pass_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(email_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addComponent(customer2)
                                .addGap(27, 27, 27)
                                .addComponent(res_owner2)
                                .addGap(18, 18, 18)
                                .addComponent(admin2))
                            .addComponent(pass_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138))))
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addComponent(email_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(pass_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(res_owner2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(68, 68, 68))
        );

        content.add(login_panel, "card3");

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void setResVisible(boolean x) {
        combo_categories.setVisible(x);
        combo_locations.setVisible(x);
        jSeparator10.setVisible(x);
        jSeparator12.setVisible(x);
        jLabel16.setVisible(x);
        jLabel19.setVisible(x);
        jLabel18.setVisible(x);
        jLabel11.setVisible(x);
        num_txt.setVisible(x);
        res_name_txt.setVisible(x);

    }

    private void fillCategoryAndLocation() {
        ArrayList<Category> categories = new ArrayList<Category>(100);
        categories = Category.getCategoryList();
        for (int i = 0; i < categories.size(); i++) {
            combo_categories.addItem(categories.get(i).getCategory_name());
        }
        ArrayList<Location> locations = new ArrayList<Location>(100);
        locations = Location.getLocationList();
        for (int i = 0; i < locations.size(); i++) {
            combo_locations.addItem(locations.get(i).getLocation_name());
        }
    }

    private void customerSignup() {
        String name = name_txt.getText();
        String email = email_txt.getText();
        String pass = new String(pass_txt.getPassword());
        Customer customer;
        try {
            customer = new Customer(email, name, pass);
            customer.insertIntoDB();

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(log_in.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("User created successfully!");

    }

    private void ownerSignup() throws NoSuchAlgorithmException {
        String name = name_txt.getText();
        String email = email_txt.getText();
        String pass = new String(pass_txt.getPassword());
        RestaurantOwner owner = new RestaurantOwner(email, name, pass);
        owner.insertIntoDB();

        String restaurant_name = res_name_txt.getText();
        String phone = num_txt.getText();
        int location_id = combo_locations.getSelectedIndex();
        int category_id = combo_categories.getSelectedIndex() + 1;
        Register.RestaurantAndOwner(owner, restaurant_name, phone, Location.getLocationList().get(location_id), category_id);

    }

    private void customerSignin(String email, String pass) {
        Customer customer = Customer.login(email, pass);
        if (customer == null) {
            System.out.println("Invalid email or password, please try again!");
        } else {
                    CustomerForm customerform = new CustomerForm();
                          customerform.setVisible(true);
                          dispose();
        }
    }

    private void ownerSignin(String email, String pass) {
        RestaurantOwner restaurantOwner = RestaurantOwner.login(email, pass);
        if (restaurantOwner == null) {
            System.out.println("Invalid email or password, please try again!");
        } else {
            System.out.println("lesa");

        }

    }

    private void adminSignin(String email, String pass) {

        Admin admin = Admin.login(email, pass);
        if (admin == null) {
            System.out.println("Invalid email or password, please try again!");
        } else {
            System.out.println("lesa");
        }
    }

            

    private void res_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res_name_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void num_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_txtActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
        setResVisible(true);
    }//GEN-LAST:event_ownerActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        setResVisible(false);
    }//GEN-LAST:event_customerActionPerformed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
signup_panel.setVisible(false);
        login_panel.setVisible(true);    }//GEN-LAST:event_jLabel6MouseClicked

    private void email_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txt2ActionPerformed

    private void customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer2ActionPerformed

    private void res_owner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_owner2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res_owner2ActionPerformed

    private void admin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
if (customer.isSelected()== true)
        {
            customerSignup();
            
        }
        else if (owner.isSelected()== true)
        {
            try {
                ownerSignup();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(log_in.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        signup_panel.setVisible(false);
        login_panel.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
jPanel2.setBackground(new java.awt.Color(255, 89, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
       jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 89, 0));  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String email = email_txt2.getText();
        String pass = new String(pass_txt2.getPassword());
        
        
        if (customer2.isSelected() == true) {
               customerSignin( email ,  pass );

        }
        
        
        
        if (res_owner2.isSelected() == true) {
             ownerSignin( email ,  pass );

        }
        
        
        
        if (admin2.isSelected() == true) {
            adminSignin( email ,  pass );
            
        }



    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
jPanel4.setBackground(new java.awt.Color(255, 89, 0));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));      }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 89, 0));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
signup_panel.setVisible(true);
        login_panel.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void pass_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the CustomerForm */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combo_categories;
    private javax.swing.JComboBox<String> combo_locations;
    private javax.swing.JPanel content;
    private javax.swing.JRadioButton customer;
    private javax.swing.JRadioButton customer2;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField email_txt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel login_panel;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField num_txt;
    private javax.swing.JRadioButton owner;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JPasswordField pass_txt2;
    private javax.swing.JTextField res_name_txt;
    private javax.swing.JRadioButton res_owner2;
    private javax.swing.JPanel signup_panel;
    // End of variables declaration//GEN-END:variables
}
class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
        }
    }
